#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar \
  position=top \
  height=35 \
  blur_radius=50 \
  #color=$BAR_COLOR
  color=unknown

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:15.0"
  icon.color=$WHITE
  label.font="Hack Nerd Font:Bold:15.0"
  label.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=10
  background.height=24
  icon.padding_left=10
  icon.padding_right=0
  label.padding_left=10
  label.padding_right=10
)
sketchybar --default "${default[@]}"

# # -- left side items --
source $ITEM_DIR/front_app.sh
SPACE_ICONS=("1" "2" "3" "4" "Q" "W" "E" "R" "A" "S" "D" "F")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=7
    icon.padding_right=7
    background.color=0x40ffffff
    background.corner_radius=5
    background.height=25
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done



# -- right side items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

sketchybar --update
