#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_created action="~/.config/yabai/scripts/float_and_center_if_alone.sh"

yabai -m space 1 --label "Browser"      # 1
yabai -m space 2 --label "Code"         # 2
yabai -m space 3 --label "Database"     # 3
yabai -m space 4 --label "API"          # 4
yabai -m space 5 --label "Docker"       # 5
yabai -m space 6 --label "Communication" # Q
yabai -m space 7 --label "Notes"        # W
yabai -m space 8 --label "Terminal"     # E
yabai -m space 9 --label "Other A"        # A
yabai -m space 10 --label "Other S"       # S
yabai -m space 11 --label "Other D"      # D
yabai -m space 12 --label "Other F"        # F

yabai -m config top_padding 20 
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 5

yabai -m config window_border on                  # Включить границы окон
yabai -m config window_border_width 2            # Толщина границы (в пикселях)
yabai -m config active_window_border_color 0xFF75B5FF  # Цвет активного окна (голубой, ARGB)
yabai -m config normal_window_border_color 0x55555555  # Цвет неактивных окон (серый, полупрозрачный)
yabai -m config window_border_radius 8           # Закругление углов (опционально)

yabai -m rule --add app="^(Outline|LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Alfred|Activity Monitor|OpenVPN Connect|Finder)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp

# yabai -m config --space 2 layout float

yabai -m rule --add app="^GoLand$" title=".*Tool Window.*" manage=off
yabai -m rule --add app="^RustRover$" title=".*Tool Window.*" manage=off

yabai -m rule --add app="^GoLand$" manage=on
yabai -m rule --add app="^RustRover$" manage=on


echo "yabai configuration loaded.."
